// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Credential struct {
	CredID    int64
	LakeID    int64
	CreatedAt pgtype.Timestamptz
	KeyID     string
	Key       string
	Region    string
}

type Epauth struct {
	AuthID   int64
	UserID   int64
	Email    string
	Password string
	Name     pgtype.Text
	Picture  pgtype.Text
}

type Goauth struct {
	AuthID  int64
	UserID  int64
	Email   string
	Name    pgtype.Text
	Picture pgtype.Text
	ID      pgtype.Text
}

type Lake struct {
	LakeID    int64
	UserID    int64
	Name      string
	Region    string
	CreatedAt pgtype.Timestamptz
	Ptype     string
}

type Location struct {
	LocID      int64
	LakeID     int64
	CreatedAt  pgtype.Timestamptz
	BucketName string
	UserID     int64
}

type Scan struct {
	ScanID    int64
	LakeID    int64
	LocID     int64
	CreatedAt pgtype.Timestamptz
}

type Setting struct {
	SetID       int64
	UserID      int64
	LastUpdated pgtype.Timestamptz
	Advmeta     bool
	Cmptview    bool
	Rfrshint    int16
	Notif       bool
	Theme       string
	Fontsz      int16
	Tooltps     bool
	Shortcuts   bool
}

type Tip struct {
	TipID int64
	Tip   string
	Hrefs [][]byte
}

type User struct {
	UserID    int64
	Email     string
	Confirmed bool
	CreatedAt pgtype.Timestamptz
	UserUuid  pgtype.UUID
	AuthType  interface{}
}
