// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getCredentials = `-- name: GetCredentials :one
SELECT cred_id, key_id, key, region 
FROM credentials 
WHERE cred_id = $1
`

func (q *Queries) GetCredentials(ctx context.Context, credID int64) (Credential, error) {
	row := q.db.QueryRow(ctx, getCredentials, credID)
	var i Credential
	err := row.Scan(
		&i.CredID,
		&i.KeyID,
		&i.Key,
		&i.Region,
	)
	return i, err
}

const insertNewCredentails = `-- name: InsertNewCredentails :exec
INSERT INTO credentials (key_id, key, region)
VALUES ($1, $2, $3)
`

type InsertNewCredentailsParams struct {
	KeyID  string
	Key    string
	Region string
}

func (q *Queries) InsertNewCredentails(ctx context.Context, arg InsertNewCredentailsParams) error {
	_, err := q.db.Exec(ctx, insertNewCredentails, arg.KeyID, arg.Key, arg.Region)
	return err
}
